### ISSUE TITLE
Connectivity testing issues

### ISSUE THREAD

**Issue by Lumysia** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#14]
Due to the problems of some government departments, mainland China can not access google.com, can the connectivity test be modified to cloudflare.com, bing.com or others?

Thank you very much for your work.

**Comment by williamtrelawny** [comment]
Or why not just remove the connectivity test altogether? If I understand correctly, it just serves to verify the host can reach the Internet  before downloading files, but couldn’t the failure to download files serve as its own indicator the host cannot reach the internet?

Plus a ping test to google, cloudflare, etc., doesn’t even necessarily prove the host has access to the site hosting the files to be downloaded anyway.

**Comment by TheRemote** [comment]
I've been doing it that way for 5 years.  I've been doing it since before the containers (which are a port from my original projects) existed.  I'm guessing the only reason that this has become an issue is because the container (and who is using it and where) has grown so much.  It's definitely time to address it it sounds like!

This probably won't surprise many of you but I *hate* any type of blocking like this.  I *hate* it when China blocks US companies and I *hate* it when the US blocks Chinese companies which I'm well aware they've done.  I don't get to decide though and I'm guessing most Chinese people using the container don't get to personally decide that for China either.

Probably what makes sense to do here is to change it to the Paper Minecraft server that it will be downloading the files from anyway.  That should not be a service that is blocked anywhere (and if it is then the container can't be working anyway by definition).

As far as why don't we just delete the check the answer is basically you will need to write code to handle a 0 byte download, a partial download, check whether the extraction succeeded and all the sudden before you know it the code is 3x as complex.  It wouldn't make it simpler to delete the check.  The check is the simplest way to prevent all of those errors.  Without it code would needed to be added to check for a whole range of failures which basically don't occur unless it can't contact the download server.

Thanks for reporting this, I'll get that changed!

**Comment by TheRemote** [comment]
This is done.  I changed it across all 4 containers and my 2 standalone projects as well.  Autobuilds should be coming up for each of them within in the next 10-15 minutes or so.

Can you give it a try (after doing a docker pull to get the latest version) and let me know if this one works properly?

**Comment by Lumysia** [comment]
It worked like a charm, thx !!!

**Comment by TheRemote** [comment]
No problem at all, enjoy and take care!
